g_name=input("Enter a girls name:")
# print("The girls name is "+g_name)
# print(f"the girls age is {g_name}")
# g_age=int(input("Enter the girls age:"))
b_name=input("enter a boy name:")
# # print("the boy name is "+b_name)
# print(f"the boy name is {b_name}")
# b_age=int(input("Enter the  boys age:"))
# print("the diffrence between the ages is "+str(g_age-b_age))
# print(f"the age diffrence btw the girl and boy is {b_age-g_age}")
# print(b_name+" loves "+g_name)
print(" ".join(f"{b_name}loves{g_name}"))
print(f"{b_name}loves{g_name}".split())
print(f"    {b_name} loves {g_name}   ".strip())
